FROM ruby:3.3.6

ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

# Node.js + Yarn セットアップ
RUN apt-get update -qq \
&& apt-get install -y ca-certificates curl gnupg \
&& mkdir -p /etc/apt/keyrings \
&& curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
&& NODE_MAJOR=20 \
&& echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
&& wget --quiet -O - /tmp/pubkey.gpg https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
&& echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update -qq && apt-get install -y build-essential libssl-dev nodejs yarn vim

# 作業ディレクトリ作成
RUN mkdir /v4_advanced_rails_2
WORKDIR /v4_advanced_rails_2

# bundler
RUN gem install bundler
COPY . /v4_advanced_rails_2
RUN yarn install
